/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.holpapp.views;

import javax.swing.JOptionPane;

import com.holpapp.controllers.DatabaseController;
import com.holpapp.models.Ad;
import com.holpapp.models.User;
import com.holpapp.views.Admin.AdminHome;
import com.holpapp.views.Helper.HelperHome;
import com.holpapp.views.Needer.NeederHome;

/**
 *
 * @author arman
 */
public class AdInfos extends javax.swing.JFrame {

    private DatabaseController db = new DatabaseController();

    private Ad adSaved;
    private User userSaved;
    

    /**
     * Creates new form AdInfos
     */
    public AdInfos(Ad ad, User user) {
        this.adSaved = ad;
        this.userSaved = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        whenLabel = new javax.swing.JLabel();
        whereLabel = new javax.swing.JLabel();
        adPostedLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        adPostedLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        unvalidateButton = new javax.swing.JButton();
        titleLabel1 = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        titleLabel4 = new javax.swing.JLabel();
        titleLabel5 = new javax.swing.JLabel();
        titleLabel6 = new javax.swing.JLabel();
        titleLabel7 = new javax.swing.JLabel();
        titleLabel8 = new javax.swing.JLabel();
        titleLabel9 = new javax.swing.JLabel();
        done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        page.setBackground(new java.awt.Color(255, 236, 245));

        titleLabel.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        titleLabel.setText("Title:");

        descLabel.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        descLabel.setText("Description:");

        whenLabel.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        whenLabel.setText("When ?:");

        whereLabel.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        whereLabel.setText("Where ?:");

        adPostedLabel.setFont(new java.awt.Font("Mluvka ExtraBold", 0, 14)); // NOI18N
        adPostedLabel.setText("Ad posted by");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        adPostedLabel1.setFont(new java.awt.Font("Mluvka ExtraBold", 0, 14)); // NOI18N
        adPostedLabel1.setText("Actions");

        backButton.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        backButton.setText("Close");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        validateButton.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        validateButton.setText("Validate");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        applyButton.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        unvalidateButton.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        unvalidateButton.setText("Unvalidate");
        unvalidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unvalidateButtonActionPerformed(evt);
            }
        });

        User userAux = db.getUserFromAd(adSaved);

        titleLabel1.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        titleLabel1.setText(adSaved.getTitle());

        titleLabel2.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        titleLabel2.setText(adSaved.getDescription());

        titleLabel3.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        titleLabel3.setText(adSaved.getAdWhen());

        titleLabel4.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        titleLabel4.setText(adSaved.getAdWhere());

        titleLabel5.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        titleLabel5.setText(userAux.getName());

        titleLabel6.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        titleLabel6.setText(userAux.getSurname());

        titleLabel7.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        if(userAux.getRole().equals("Helper")){
            titleLabel7.setText("Skills : "+db.getHelperFromUser(userAux).getSkills());
        }else{
            titleLabel7.setText("Diseases : "+db.getNeederFromUser(userAux).getDiseases());
        }

        titleLabel8.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        if(userAux.getRole().equals("Helper")){
            titleLabel8.setText("Availability : "+db.getHelperFromUser(userAux).getAvailability());
        }else{
            titleLabel8.setText("Availability : "+db.getNeederFromUser(userAux).getAvailability());
        }

        titleLabel9.setFont(new java.awt.Font("Mluvka Light", 0, 14)); // NOI18N
        titleLabel9.setText("grade");

        done.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pageLayout = new javax.swing.GroupLayout(page);
        page.setLayout(pageLayout);
        pageLayout.setHorizontalGroup(
            pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(361, 361, 361))
            .addGroup(pageLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pageLayout.createSequentialGroup()
                        .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel5)
                            .addComponent(titleLabel6)
                            .addComponent(titleLabel7)
                            .addGroup(pageLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(adPostedLabel))
                            .addComponent(titleLabel8)
                            .addComponent(titleLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pageLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(adPostedLabel1)
                                .addGap(163, 163, 163))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageLayout.createSequentialGroup()
                                        .addComponent(applyButton)
                                        .addGap(153, 153, 153))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageLayout.createSequentialGroup()
                                        .addComponent(validateButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(unvalidateButton)
                                        .addGap(84, 84, 84))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageLayout.createSequentialGroup()
                                        .addComponent(done)
                                        .addGap(155, 155, 155))))))
                    .addGroup(pageLayout.createSequentialGroup()
                        .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLabel)
                            .addComponent(titleLabel)
                            .addComponent(whenLabel)
                            .addComponent(whereLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel4)
                            .addComponent(titleLabel3)
                            .addComponent(titleLabel1)
                            .addComponent(titleLabel2))
                        .addContainerGap())))
        );
        pageLayout.setVerticalGroup(
            pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(titleLabel2))
                .addGap(28, 28, 28)
                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whenLabel)
                    .addComponent(titleLabel3))
                .addGap(28, 28, 28)
                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whereLabel)
                    .addComponent(titleLabel4))
                .addGap(55, 55, 55)
                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pageLayout.createSequentialGroup()
                        .addComponent(adPostedLabel)
                        .addGap(21, 21, 21)
                        .addComponent(titleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pageLayout.createSequentialGroup()
                        .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pageLayout.createSequentialGroup()
                                .addComponent(adPostedLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(applyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(validateButton)
                                    .addComponent(unvalidateButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(done))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        if(userSaved.getRole().equals("Admin")){
            applyButton.setVisible(false);
            validateButton.setVisible(true);
            unvalidateButton.setVisible(true);
            done.setVisible(false);
        }else if(adSaved.isDone()){
            applyButton.setVisible(false);
            validateButton.setVisible(false);
            unvalidateButton.setVisible(false);
            done.setVisible(false);
        }else if(adSaved.getBeneficiary().equals(userSaved.getId())){
            applyButton.setVisible(false);
            validateButton.setVisible(false);
            unvalidateButton.setVisible(false);
            done.setVisible(true);
        }else{
            applyButton.setVisible(true);
            validateButton.setVisible(false);
            unvalidateButton.setVisible(false);
            done.setVisible(false);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        if (adSaved != null) {
                    
            boolean isValidationSuccessful = db.validateAd(adSaved);
            
            if (isValidationSuccessful) {
                JOptionPane.showMessageDialog(null, "Validation successful !", "Validation successful !", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Validation did not success", "Validation did not success", JOptionPane.ERROR_MESSAGE);
            }
        } else {
           JOptionPane.showMessageDialog(null, "Ad null", "Ad null", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_validateButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        if (adSaved != null) {
                    
            boolean link = db.linkAdBenef(adSaved,userSaved);
            
            if (link) {
                JOptionPane.showMessageDialog(null, "Apply successful !", "Apply successful !", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Apply did not success", "Apply did not success", JOptionPane.ERROR_MESSAGE);
            }
        } else {
           JOptionPane.showMessageDialog(null, "Ad null", "Ad null", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    private void unvalidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unvalidateButtonActionPerformed
        if (adSaved != null) {
                    
            boolean isinValidationSuccessful = db.invalidateAd(adSaved);
            
            if (isinValidationSuccessful) {
                JOptionPane.showMessageDialog(null, "evt", "Invalidation successful !", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "evt", "Invalidation did not success", JOptionPane.ERROR_MESSAGE);
            }
        } else {
           JOptionPane.showMessageDialog(null, "evt", "Ad null", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_unvalidateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if(userSaved.getRole().equals("Admin")){
            AdminHome adminPage = new AdminHome(userSaved);
            adminPage.setVisible(true);
        }else if(userSaved.getRole().equals("Helper")){
            HelperHome helperPage = new HelperHome(userSaved);
            helperPage.setVisible(true);
        }else if(userSaved.getRole().equals("Needer")){
            NeederHome neederPage = new NeederHome(userSaved);
            neederPage.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        if(adSaved!=null){
            boolean isDoneSuccessful = db.setDone(adSaved);
            if(isDoneSuccessful){
                JOptionPane.showMessageDialog(null, "Done successful !", "Done successful !", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Done did not success", "Done did not success", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdInfos(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adPostedLabel;
    private javax.swing.JLabel adPostedLabel1;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel descLabel;
    private javax.swing.JButton done;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel page;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    private javax.swing.JLabel titleLabel4;
    private javax.swing.JLabel titleLabel5;
    private javax.swing.JLabel titleLabel6;
    private javax.swing.JLabel titleLabel7;
    private javax.swing.JLabel titleLabel8;
    private javax.swing.JLabel titleLabel9;
    private javax.swing.JButton unvalidateButton;
    private javax.swing.JButton validateButton;
    private javax.swing.JLabel whenLabel;
    private javax.swing.JLabel whereLabel;
    // End of variables declaration//GEN-END:variables
}
