/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.holpapp.views;

import java.awt.Dimension;
import java.util.List;

import javax.swing.Box;
import javax.swing.JOptionPane;

import com.holpapp.components.adComp;
import com.holpapp.controllers.DatabaseController;
import com.holpapp.models.Ad;
import com.holpapp.models.User;
import com.holpapp.views.Admin.AdminHome;
import com.holpapp.views.Helper.HelperHome;
import com.holpapp.views.Needer.NeederHome;

import net.miginfocom.swing.MigLayout;

/**
 *
 * @author arman
 */
public class AdList extends javax.swing.JFrame {

    private User userSaved;
    private List<Ad> ads;
    

    /**
     * Creates new form AdList
     */
    public AdList(User user, String type) {
        this.userSaved = user;
        initComponents();
        adList.setLayout(new MigLayout("fillx, wrap 1", "center", ""));
        DatabaseController databaseController = new DatabaseController();
        if (type.equals("created")) {
            this.ads = databaseController.getCreatedAds(user);
        } else {
            this.ads = databaseController.getBenefAds(user);
        }
        
        for (Ad ad : ads) {
            
                adComp adComp = new adComp(ad,userSaved);
                adList.add(Box.createRigidArea(new Dimension(0, 15))); 
                adList.add(adComp, "growx");
            
        }

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adList = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adList.setBackground(new java.awt.Color(255, 236, 245));
        adList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                adListComponentShown(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Mluvka SemiBold", 0, 14)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adListLayout = new javax.swing.GroupLayout(adList);
        adList.setLayout(adListLayout);
        adListLayout.setHorizontalGroup(
            adListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adListLayout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(closeButton)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        adListLayout.setVerticalGroup(
            adListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adListLayout.createSequentialGroup()
                .addContainerGap(513, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(28, 28, 28))
        );

        jScrollPane1.setViewportView(adList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed

        if(userSaved.getRole().equals("Admin")){
            AdminHome adminPage = new AdminHome(userSaved);
            adminPage.setVisible(true);
        }else if(userSaved.getRole().equals("Helper")){
            HelperHome helperPage = new HelperHome(userSaved);
            helperPage.setVisible(true);
        }else if(userSaved.getRole().equals("Needer")){
            NeederHome neederPage = new NeederHome(userSaved);
            neederPage.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void adListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_adListComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_adListComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdList(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adList;
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
