/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.holpapp.views;
import javax.swing.JOptionPane;

import com.holpapp.controllers.DatabaseController;
import com.holpapp.models.User;
import com.holpapp.views.Admin.AdminHome;
import com.holpapp.views.Helper.HelperHome;
import com.holpapp.views.Needer.NeederHome;

/**
 *
 * @author arman
 */
public class loginForm extends javax.swing.JFrame {

    private int eCount;
    private int pCount;

    /**
     * Creates new form Needer_Formdd
     */
    public loginForm() {
        initComponents();
        eCount=0;
        pCount=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        moto = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        emailSeparator = new javax.swing.JSeparator();
        passwordSeparator = new javax.swing.JSeparator();
        signupButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        alreadyText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 240, 208));

        mainPanel.setBackground(new java.awt.Color(255, 240, 230));

        leftPanel.setBackground(new java.awt.Color(255, 208, 230));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoholp.png"))); // NOI18N

        moto.setFont(new java.awt.Font("Mluvka Bold", 0, 14)); // NOI18N
        moto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moto.setText("Un besoin ? Et holp !");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(moto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(255, 236, 245));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordField.setBackground(new java.awt.Color(255, 236, 245));
        passwordField.setFont(new java.awt.Font("Mluvka Light", 0, 12)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setText("jPasswordField1");
        passwordField.setBorder(null);
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        rightPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 174, 31));

        emailSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(emailSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, 10));

        passwordSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 110, 10));

        signupButton.setBackground(new java.awt.Color(255, 208, 230));
        signupButton.setFont(new java.awt.Font("Mluvka Medium", 0, 12)); // NOI18N
        signupButton.setText("Sign Up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        rightPanel.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        emailField.setBackground(new java.awt.Color(255, 236, 245));
        emailField.setFont(new java.awt.Font("Mluvka SemiBold", 0, 12)); // NOI18N
        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailField.setText("Email");
        emailField.setBorder(null);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        rightPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 174, 30));

        loginButton.setBackground(new java.awt.Color(255, 208, 230));
        loginButton.setFont(new java.awt.Font("Mluvka Medium", 0, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        rightPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        alreadyText.setFont(new java.awt.Font("Mluvka ExtraLight", 0, 12)); // NOI18N
        alreadyText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alreadyText.setText("Don't have an account ?");
        rightPanel.add(alreadyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        registerForm registerForm = new registerForm();
        registerForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String email = emailField.getText();
        String password = new String(passwordField.getPassword());
        DatabaseController databaseController = new DatabaseController();
    
        User user = databaseController.checkUser(email, password);
    
        if (user != null) {
            // Vérifiez le rôle de l'utilisateur
            String role = user.getRole();
    
            if ("Helper".equals(role)) {
                // Ouvrez la fenêtre HelperHome
                HelperHome helperHome = new HelperHome(user);
                helperHome.setVisible(true);
                this.dispose();
            } else if ("Needer".equals(role)) {
                
                NeederHome neederHome = new NeederHome(user);
                neederHome.setVisible(true);
                this.dispose();
            } else if ("Admin".equals(role)) {
                
                AdminHome adminHome = new AdminHome(user);
                adminHome.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Unknown role: " + role);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Wrong information");
        }
    }
    
    //GEN-LAST:event_loginButtonActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        if(eCount==0){
            emailField.setText("");
        }
        eCount++;
    }//GEN-LAST:event_emailFieldFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if(pCount==0){
            passwordField.setText("");
        }
        pCount++;
    }//GEN-LAST:event_passwordFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        if(emailField.getText().isEmpty()){
            emailField.setText("Email");
            eCount=0;
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if(passwordField.getPassword().length==0){
            passwordField.setText("Password");
            pCount=0;
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyText;
    private javax.swing.JTextField emailField;
    private javax.swing.JSeparator emailSeparator;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel moto;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton signupButton;
    // End of variables declaration//GEN-END:variables
}
