/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.holpapp.views;
import javax.swing.*;


import com.holpapp.controllers.DatabaseController;

/**
 *
 * @author arman
 */
public class registerForm extends javax.swing.JFrame {

    /**
     * Creates new form Needer_Form
     */
    public registerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        moto = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        nameSeparator = new javax.swing.JSeparator();
        passwordSeparator = new javax.swing.JSeparator();
        loginButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        signupButton = new javax.swing.JButton();
        surnameSeparator = new javax.swing.JSeparator();
        surnameField = new javax.swing.JTextField();
        addressSeparator = new javax.swing.JSeparator();
        addressField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        phoneSeparator = new javax.swing.JSeparator();
        birthdateSeparator = new javax.swing.JSeparator();
        birthdateField = new javax.swing.JTextField();
        emailSeparator = new javax.swing.JSeparator();
        emailField = new javax.swing.JTextField();
        confirmPasswordSeparator = new javax.swing.JSeparator();
        confirmPasswordField = new javax.swing.JPasswordField();
        alreadyText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 240, 208));

        mainPanel.setBackground(new java.awt.Color(255, 240, 230));

        leftPanel.setBackground(new java.awt.Color(255, 208, 230));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/holpapp/views/logoholp.png"))); // NOI18N

        moto.setFont(new java.awt.Font("Mluvka Bold", 0, 14)); // NOI18N
        moto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moto.setText("Un besoin ? Et holp !");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(moto)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(255, 236, 245));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordField.setBackground(new java.awt.Color(255, 236, 245));
        passwordField.setFont(new java.awt.Font("Mluvka Light", 0, 12)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setText("Password");
        passwordField.setBorder(null);
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        rightPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 174, 31));

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(nameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 10));

        passwordSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 110, 10));

        loginButton.setBackground(new java.awt.Color(255, 208, 230));
        loginButton.setFont(new java.awt.Font("Mluvka Medium", 0, 12)); // NOI18N
        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        rightPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, -1, -1));

        nameField.setBackground(new java.awt.Color(255, 236, 245));
        nameField.setFont(new java.awt.Font("Mluvka SemiBold", 0, 12)); // NOI18N
        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameField.setText("Name");
        nameField.setBorder(null);
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        rightPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 174, 30));

        signupButton.setBackground(new java.awt.Color(255, 208, 230));
        signupButton.setFont(new java.awt.Font("Mluvka Medium", 0, 12)); // NOI18N
        signupButton.setText("Sign Up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        rightPanel.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        surnameSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(surnameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, 10));

        surnameField.setBackground(new java.awt.Color(255, 236, 245));
        surnameField.setFont(new java.awt.Font("Mluvka SemiBold", 0, 12)); // NOI18N
        surnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        surnameField.setText("Surname");
        surnameField.setBorder(null);
        surnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surnameFieldFocusGained(evt);
            }
        });
        surnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameFieldActionPerformed(evt);
            }
        });
        rightPanel.add(surnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 174, 30));

        addressSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(addressSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 110, 10));

        addressField.setBackground(new java.awt.Color(255, 236, 245));
        addressField.setFont(new java.awt.Font("Mluvka SemiBold", 0, 12)); // NOI18N
        addressField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addressField.setText("Address");
        addressField.setBorder(null);
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
        });
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        rightPanel.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 174, 30));

        phoneField.setBackground(new java.awt.Color(255, 236, 245));
        phoneField.setFont(new java.awt.Font("Mluvka SemiBold", 0, 12)); // NOI18N
        phoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phoneField.setText("Phone");
        phoneField.setBorder(null);
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFieldFocusGained(evt);
            }
        });
        rightPanel.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 174, 30));

        phoneSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(phoneSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, 10));

        birthdateSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(birthdateSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, 10));

        birthdateField.setBackground(new java.awt.Color(255, 236, 245));
        birthdateField.setFont(new java.awt.Font("Mluvka SemiBold", 0, 12)); // NOI18N
        birthdateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        birthdateField.setText("Birthdate (YYYY-MM-DD)");
        birthdateField.setBorder(null);
        birthdateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthdateFieldFocusGained(evt);
            }
        });
        rightPanel.add(birthdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 174, 30));

        emailSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(emailSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, 10));

        emailField.setBackground(new java.awt.Color(255, 236, 245));
        emailField.setFont(new java.awt.Font("Mluvka SemiBold", 0, 12)); // NOI18N
        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailField.setText("Email");
        emailField.setBorder(null);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        rightPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 174, 30));

        confirmPasswordSeparator.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.add(confirmPasswordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 110, 10));

        confirmPasswordField.setBackground(new java.awt.Color(255, 236, 245));
        confirmPasswordField.setFont(new java.awt.Font("Mluvka Light", 0, 12)); // NOI18N
        confirmPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPasswordField.setText("Password");
        confirmPasswordField.setToolTipText("Password");
        confirmPasswordField.setBorder(null);
        confirmPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordFieldFocusGained(evt);
            }
        });
        rightPanel.add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 174, 31));

        alreadyText.setFont(new java.awt.Font("Mluvka ExtraLight", 0, 12)); // NOI18N
        alreadyText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alreadyText.setText("Already have an account ?");
        rightPanel.add(alreadyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        loginForm loginForm = new loginForm();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed


    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
                String name = nameField.getText();
                String surname = surnameField.getText();
                String birthdate = birthdateField.getText();
                String email = emailField.getText();
                String phone = phoneField.getText();
                String address = addressField.getText();
                String password = new String(passwordField.getPassword());
                String confirmPassword = new String(confirmPasswordField.getPassword());

                DatabaseController databaseController = new DatabaseController();
        
                if (password.equals(confirmPassword)) {
                    if (databaseController.insertUser(name, surname, birthdate, email, phone, address, password)) {
                        JOptionPane.showMessageDialog(null, "Successfully registered !");
                        nameField.setText("Name");
                        surnameField.setText("Surname");
                        birthdateField.setText("Birthdate");
                        emailField.setText("Email");
                        phoneField.setText("Phone");
                        addressField.setText("Address");
                        passwordField.setText("Password");
                        confirmPasswordField.setText("Password");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Passwords are not matching", "Error", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_signupButtonActionPerformed

    private void surnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        nameField.setText("");
    }//GEN-LAST:event_nameFieldFocusGained

    private void surnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameFieldFocusGained
        surnameField.setText("");
    }//GEN-LAST:event_surnameFieldFocusGained

    private void birthdateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthdateFieldFocusGained
        birthdateField.setText("");
    }//GEN-LAST:event_birthdateFieldFocusGained

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        emailField.setText("");
    }//GEN-LAST:event_emailFieldFocusGained

    private void phoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusGained
        phoneField.setText("");
    }//GEN-LAST:event_phoneFieldFocusGained

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
        addressField.setText("");
    }//GEN-LAST:event_addressFieldFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        passwordField.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void confirmPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFieldFocusGained
        confirmPasswordField.setText("");
    }//GEN-LAST:event_confirmPasswordFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JSeparator addressSeparator;
    private javax.swing.JLabel alreadyText;
    private javax.swing.JTextField birthdateField;
    private javax.swing.JSeparator birthdateSeparator;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JSeparator confirmPasswordSeparator;
    private javax.swing.JTextField emailField;
    private javax.swing.JSeparator emailSeparator;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel moto;
    private javax.swing.JTextField nameField;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JTextField phoneField;
    private javax.swing.JSeparator phoneSeparator;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField surnameField;
    private javax.swing.JSeparator surnameSeparator;
    // End of variables declaration//GEN-END:variables
}
