/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.holpapp.components;

import javax.swing.SwingUtilities;

import com.holpapp.models.Ad;
import com.holpapp.models.User;
import com.holpapp.views.AdInfos;

/**
 *
 * @author arman
 */
public class adComp extends javax.swing.JPanel {

    private Ad ad;
    private User userSaved;

    /**
     * Creates new form ad
     */
    public adComp(Ad ad, User user) {
        this.ad = ad;
        this.userSaved = user;
        initComponents();
        adName.setText(ad.getTitle());
        adDesc.setText(ad.getDescription());
        adTime.setText(ad.getAdWhen());

        String priority = ad.getPriority();
        if ("Low".equals(priority)) {
            exclam.setForeground(new java.awt.Color(0, 128, 0)); // Vert
        } else if ("Medium".equals(priority)) {
            exclam.setText("!!");
            exclam.setForeground(new java.awt.Color(255, 165, 0)); // Orange
        } else if ("High".equals(priority)) {
            exclam.setText("!!!");
            exclam.setForeground(new java.awt.Color(255, 0, 0)); // Rouge
        }
        if(ad.isDone()){
            exclam.setText(" ");
            exclam.setForeground(new java.awt.Color(0, 128, 0)); // Vert
            setBackground(new java.awt.Color(210, 255, 228));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adName = new javax.swing.JLabel();
        adDesc = new javax.swing.JLabel();
        adTime = new javax.swing.JLabel();
        exclam = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 252, 254));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 43, 43), 3, true));
        setMaximumSize(new java.awt.Dimension(660, 120));
        setMinimumSize(new java.awt.Dimension(660, 120));
        setPreferredSize(new java.awt.Dimension(660, 120));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        adName.setFont(new java.awt.Font("Mluvka Bold", 0, 18)); // NOI18N
        adName.setText("Title");

        adDesc.setFont(new java.awt.Font("Mluvka Medium", 0, 14)); // NOI18N
        adDesc.setText("Description");

        adTime.setFont(new java.awt.Font("Mluvka Light", 0, 12)); // NOI18N
        adTime.setText("When");

        exclam.setFont(new java.awt.Font("Mluvka ExtraBold", 0, 48)); // NOI18N
        exclam.setText("!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adTime, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adName, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(exclam)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(exclam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        AdInfos adInfos = new AdInfos(ad,userSaved);
        adInfos.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adDesc;
    private javax.swing.JLabel adName;
    private javax.swing.JLabel adTime;
    private javax.swing.JLabel exclam;
    // End of variables declaration//GEN-END:variables
}
